server:
  port: 8001

mybatis:
  type-aliases-package: com.theOne.springcloud.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  application:
    name: departmentProvider
  datasource:
    username: root
    password: 20001017
    url: jdbc:mysql://localhost:3306/xyc?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/